apiVersion: v1
kind: Service
metadata:
  name: ftps
spec:
  type: NodePort
  selector:
    app: ftps
  ports:
    - name: ftps
      port: 21
      nodePort: 21
    - name: ftps-passive
      port: 30020
      nodePort: 30020

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
spec:
  selector:
    matchLabels:
      app: ftps
  replicas: 1
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_img
        imagePullPolicy: Never
        securityContext:
          privileged: true
        env:
        - name: MINIKUBE_IP
          valueFrom:
            configMapKeyRef:
              name: ft-services-config
              key: mk-ip
        - name: USER
          valueFrom:
            configMapKeyRef:
              name: ft-services-config
              key: user
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: ft-services-secret
              key: password
        livenessProbe:
          exec:
            command:
            - pgrep
            - vsftpd
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
          - containerPort: 21
          - containerPort: 30020