kind: Service
apiVersion: v1
metadata:
  name: ftps
spec:
  type: NodePort
  selector:
    app: ftps
  ports:
    - name: ftps
      port: 21
      nodePort: 21
    - name: ftps-passive
      port: 30021
      nodePort: 30021

---

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ftps-deployment
spec:
  selector:
    matchLabels:
      app: ftps
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_img
        imagePullPolicy: Never
        securityContext:
          privileged: true
        env:
        - name: USER
          valueFrom:
            configMapKeyRef:
              name: ft-services-config
              key: user
        - name: PASSWORD
          valueFrom:
            configMapKeyRef:
              name: ft-services-config
              key: password
      # ports:
        # - containerPort: 21