apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - name: grafana
      port: 3000
      protocol: TCP
      nodePort: 3000
      targetPort: 3000
---

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: grafana-deployment
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana_img
        imagePullPolicy: Never
        securityContext:
          privileged: true
        env:
        - name: MINIKUBE_IP
          valueFrom:
            configMapKeyRef:
              name: ft-services-config
              key: mk-ip
        - name: USER
          valueFrom:
            configMapKeyRef:
              name: ft-services-config
              key: user
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: ft-services-secret
              key: password
        ports:
        - containerPort: 3000