apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    #nginx.ingress.kubernetes.io/rewrite-target: /$1
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
    # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  backend:
    serviceName: nginx
    servicePort: 80
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80
      # - path: /
      #   backend:
      #     serviceName: nginx
      #     servicePort: 443
      # - path: /grafana(/|$)(.*)
      #   backend:
      #     serviceName: grafana
      #     servicePort: 3000
      # - path: /wordpress(/|$)(.*)
      #   backend:
      #     serviceName: wordpress
      #     servicePort: 5050
      # - path: /phpmyadmin(/|$)(.*)
      #   backend:
      #     serviceName: phpmyadmin
      #     servicePort: 5000