apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  type: NodePort
  selector:
    app: phpmyadmin
  ports:
    - name: pma
      port: 5000
      nodePort: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma-deployment
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin_img
        imagePullPolicy: Never
        # command: ["sh", "-c", "tail -f /dev/null"]
        securityContext:
          privileged: true
        env:
        - name: MINIKUBE_IP
          valueFrom:
            configMapKeyRef:
              name: ft-services-config
              key: mk-ip
        - name: USER
          valueFrom:
            configMapKeyRef:
              name: ft-services-config
              key: user
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: ft-services-secret
              key: password
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /www
          # readOnly: true
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim