apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  type: NodePort
  selector:
    app: phpmyadmin
  ports:
    - name: pma
      port: 5000
      protocol: TCP
      nodePort: 5000
      targetPort: 5000
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma-deployment
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin_img
        imagePullPolicy: Never
        securityContext:
          privileged: true
        env:
        - name: MINIKUBE_IP
          valueFrom:
            configMapKeyRef:
              name: ft-services-config
              key: mk-ip
        - name: USER
          valueFrom:
            configMapKeyRef:
              name: ft-services-config
              key: user
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: ft-services-secret
              key: password
        ports:
        - containerPort: 5000
