kind: Service
apiVersion: v1
metadata:
  name: telegraf
spec:
  type: NodePort
  selector:
    app: telegraf
  ports:
    - name: telegraf
      port: 7906

---

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: telegraf-deployment
spec:
  selector:
    matchLabels:
      app: telegraf
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - name: telegraf
        image: telegraf_img
        imagePullPolicy: Never
        securityContext:
          privileged: true
        env:
        - name: MINIKUBE_IP
          valueFrom:
            configMapKeyRef:
              name: ft-services-config
              key: mk-ip
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-socket
          readOnly: true
      volumes:
      - name: docker-socket
        hostPath:
      # chemin du dossier sur l'hôte
          path: /var/run/docker.sock
          # ce champ est optionnel
          type: Socket
      # ports:
      # - containerPort: 80