apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: telegraf-deployment
spec:
  selector:
    matchLabels:
      app: telegraf
  replicas: 1
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - name: telegraf
        image: telegraf_img
        imagePullPolicy: Never
        securityContext:
          privileged: true
        env:
        - name: USER
          valueFrom:
            configMapKeyRef:
              name: ft-services-config
              key: user
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-socket
          readOnly: true
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
          type: Socket
      # ports:
      # - containerPort: 80

# kind: Service
# apiVersion: v1
# metadata:
#   name: telegraf
# spec:
#   type: NodePort
#   selector:
#     app: telegraf
#   ports:
#     - name: telegraf
#       port: 7906

# ---
