# apiVersion: v1
# kind: PersistentVolume
# metadata:
#    name: pv-wordpress 
# spec:
#   capacity:
#     storage: 50Mi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: /data-wp
#     type: DirectoryOrCreate

# ---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  #storageClassName: yourClass

---

# kind: PersistentVolume
# apiVersion: v1
# metadata:
#    name: pv-influxdb 
# spec:
#   capacity:
#     storage: 50Mi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: /data
#     type: DirectoryOrCreate

# ---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-influxdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  #storageClassName: yourClass