apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-claim
spec:
  storageClassName: idb
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  #storageClassName: yourClass
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: influxdb-pv-volume 
spec:
  storageClassName: idb
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/idb
    type: DirectoryOrCreate