# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: wp-pv-volume
#   labels:
#     app: wordpress
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 200Mi
#   accessModes:
#     - ReadWriteMany
#   hostPath:
#     path: "/data/wp"
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: wp-pv-claim
#   labels:
#     app: wordpress
# spec:
#   storageClassName: manual
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 200Mi

---

apiVersion: v1
kind: PersistentVolume
metadata:
   name: influxdb-pv-volume 
spec:
  storageClassName: idb
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/idb
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-claim
spec:
  storageClassName: idb
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  #storageClassName: yourClass